/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 23-feb-2015, 21.03.10
 */

package social_network;

import java.sql.*;
import javax.swing.*;
import java.util.regex.*;

/**
 * Frame principale
 *
 * @author Berezyuk Alina N86/618
 * @author Di Lucrezia Roberto N86/659
 * 
 */
public class Main extends javax.swing.JFrame {

    public static final int PREMUTO_ANNULLA = 0;
    public static final int PREMUTO_LOGIN = 1;

    /** Creates new form Main */
    public Main() {
        initComponents();
      Login l;
      l = new Login(this, true);
      l.setVisible(true);
      if (l.getBottonePremuto() == Login.PREMUTO_ANNULLA) {
         dispose();
      } else {
         setVisible(true);
      }
    }

   private int bottonePremuto;

   public int getBottonePremuto() {
      return bottonePremuto;
   }

   protected PreparedStatement getComandoAccedi(Connection c)
           throws SQLException {
      String query;
      PreparedStatement st;

      query = "select count(*) from " + Database.schema + ".account where username = ? and password = ?";

      st = c.prepareStatement(query);
      st.setString(1, tUsername.getText().toUpperCase());
      st.setString(2, new String(tPassword.getPassword()));

      return st;
   }

   protected boolean eseguiAvanti(Connection con) {
      return true;
   }

    /**
    * Mostra una descrizione di un errore SQL in un linguaggio comprensibile per
    * l'utente finale. <br> L'implementazione di DBFrame fa eccezione, essa
    * fornisce un messaggio standard per gli errori non previsti esplicitamente.
    *
    */
   protected void mostraErrori(SQLException e) {
      mostraErrori(e, "", 0);
   }

   /**
    * Mostra una descrizione di un errore SQL in un linguaggio comprensibile per
    * l'utente finale. <br> L'implementazione di DBFrame fa eccezione, essa
    * fornisce un messaggio standard per gli errori non previsti esplicitamente.
    *
    * @param e eccezione SQLException catturata
    * @param query l'istruzione SQL che ha causato l'errore
    * @param contesto intero per distinguere se l'eccezione ha avuto origine
    * da una query
    */
   protected void mostraErrori(SQLException e, String query, int contesto) {
      String msg;
      if ((e.getErrorCode() == 17068 | e.getErrorCode() == 17011) &
              contesto == 0) {
         return; //questo errore non mi interessa
      }
      msg = "ErrorCode= " + e.getErrorCode() + "\n";
      msg += "Message= " + e.getMessage() + "\n";
      msg += "SQLState= " + e.getSQLState() + "\n";

      JOptionPane.showMessageDialog(this, msg, "Errore",
              JOptionPane.ERROR_MESSAGE);
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tTitolo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bRegistrazione = new javax.swing.JButton();
        bChiudi = new javax.swing.JButton();
        tUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bAccedi = new javax.swing.JButton();
        tPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Social Network");

        tTitolo.setFont(tTitolo.getFont().deriveFont((tTitolo.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, 20));
        tTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTitolo.setText("Social Network");
        tTitolo.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel2.setText("Accedi con i tuoi dati personali");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel4.setText("o Registra un nuovo utente");

        bRegistrazione.setText("Registrazione");
        bRegistrazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrazioneActionPerformed(evt);
            }
        });

        bChiudi.setText("Chiudi");
        bChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChiudiActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel3.setText("Password");

        bAccedi.setText("Accedi");
        bAccedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccediActionPerformed(evt);
            }
        });

        tPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(bChiudi)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tPassword)
                                .addComponent(tUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(bAccedi))))
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(bRegistrazione)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bAccedi)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRegistrazione)
                .addGap(25, 25, 25)
                .addComponent(bChiudi)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChiudiActionPerformed
       bottonePremuto = PREMUTO_ANNULLA;
       dispose();
    }//GEN-LAST:event_bChiudiActionPerformed

    private void bRegistrazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrazioneActionPerformed
        registrazione();
    }//GEN-LAST:event_bRegistrazioneActionPerformed

    private void bAccediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccediActionPerformed
       PreparedStatement st;
       ResultSet ret;
       Connection c = null;
       int count;

       try {
          c = Database.nuovaConnessione();

          st = getComandoAccedi(c);

          System.out.println(1);
          c.setAutoCommit(false);
          ret = st.executeQuery();
          if (ret.next()){
              count = ret.getInt(1);
              if(count > 0){
                System.out.println(10);
                accedi();
            }else{
              String msg;
              msg = "Username o Password errati";
              JOptionPane.showMessageDialog(this, msg, "Information", JOptionPane.WARNING_MESSAGE );
            }
          }
          c.setAutoCommit(true);
          System.out.println(100);

       } catch (SQLException e) {
          mostraErrori(e);
       }
    }//GEN-LAST:event_bAccediActionPerformed

    private void tPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPasswordActionPerformed

    /**
    * @param args the command line arguments
    */

    private void accedi(){
        Account a;
        a = new Account();
        a.setVisible(true);
    }

    private void registrazione() {
      Registrazione r;
      r = new Registrazione();
      r.setVisible(true);
   }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main m = new Main();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccedi;
    private javax.swing.JButton bChiudi;
    private javax.swing.JButton bRegistrazione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JLabel tTitolo;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables

}
